---
site_name: BIDS Apps execution specification
site_url: https://bids-specification.readthedocs.io/en/stable/
nav:
- Specification:
  - Specification: specification.md
  - Contributors: CONTRIBUTING.md
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
copyright: Copyright &copy; 2023, BIDS execution Contributors - <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>
extra:
  generator: false
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/BIDSstandard/
  - icon: fontawesome/brands/github
    link: https://github.com/bids-standard/execution-spec.git
  - icon: fontawesome/brands/google
    link: https://groups.google.com/g/bids-discussion
markdown_extensions:
- toc:
    anchorlink: true
- pymdownx.superfences
plugins:
- search
docs_dir: src
use_directory_urls: false
